version: '3.8'

services:
  python_app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./logs:/app/logs  
      - ./server/.env:/app/.env
    restart: always
