FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y cron

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN if [ ! -e /usr/local/bin/python ]; then ln -s /usr/local/bin/python3 /usr/local/bin/python; fi

COPY crontab /etc/cron.d/scheduled_jobs
RUN chmod 0644 /etc/cron.d/scheduled_jobs

RUN crontab /etc/cron.d/scheduled_jobs

CMD ["cron", "-f"]
